### PR TITLE
PR for adding Action Engine (AE) version of the navX Library for LabVIEW

### PR DESCRIPTION
**Pull request by aeastet**
Here is the pull request for all of the work we did on navX AE version.

### CODE REVIEW

**Comment by jrjparks** [comment]
I'll look into merging this over the weekend if I get some free time. I'll need to clean the project up before I accept PR #15.

**Comment by aeastet** [comment]
No problem. I was just looking to see if I could figure out how to do the
pull request. I hope I did it correctly. Let me know if I did something
wrong.

On Fri, May 13, 2016 at 11:14 AM, James R.J. Parks <notifications@github.com

**Comment by jrjparks** [comment]
Merged into development manually.

**Comment by aeastet** [comment]
Hi James,

I added the ability for the system to run up to 10 different devices at one
time. I added the example to the navXAE v1 example. When you get a chance
can you try it out and let me know if it works?

Thanks,

Tim

**Comment by jrjparks** [comment]
New pull request please.

**Comment by aeastet** [comment]
How do I make sure that we are up to date with each other. I tried to
compare and sync everything but I am not sure if I am up to date with you.

I will submit the pull request in just a couple of minutes.

Thanks,

Tim

On Fri, May 20, 2016 at 12:47 PM, James R.J. Parks <notifications@github.com

**Pull request closed without merging**
